### ISSUE TITLE
pd.read_json

### ISSUE THREAD

**Issue by Servando1990** [Malachov/mydatapreprocessing#1]
Hi, Have you considered pd.read_json() instead of json.load()?

Amazing work btw

**Comment by Malachov** [comment]
Hi Servando,

thank you very much for the tip...

Json library is used because pandas version have more versions of orient ('split', 'columns', 'records', 'index' ), json automatically create list or dict based on json structure and i can apply the same processing as for other dict or list and just define whether its columns or rows. Json is python built in library, so no bigger requirements.

But of course just with couple of if lines (the same as in dict / list processing) pandas version could be used as well...

Maybe the result would be more efficient - but as i've use it as preprocessing for machile learning models, that are much more power consuming, i've rather concentrated on new features than on computing.

I hope, this small library helped you...   If you want to participate welcome : ] (for example if you think, that pd.read_json is good idea, feel free to anything and just ), 

Daniel
